services:
  mysql8:
    image: mysql:8.0
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 3306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping']
      timeout: 5s
      interval: 10s
      retries: 3
  mysql5:
    image: mysql:5.7
    environment:
      - MYSQL_DATABASE=test
      - MYSQL_USER=user
      - MYSQL_PASSWORD=pass
      - MYSQL_ROOT_PASSWORD=pass
    ports:
      - 53306:3306
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping']
      timeout: 5s
      interval: 10s
      retries: 3
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    healthcheck:
      test: ['CMD', 'pg_isready']
      timeout: 5s
      interval: 10s
      retries: 5
    ports:
      - 5432:5432
  mariadb:
    image: mariadb:10.6
    environment:
      - MARIADB_DATABASE=test
      - MARIADB_USER=user
      - MARIADB_PASSWORD=pass
      - MARIADB_ROOT_PASSWORD=pass
    ports:
      - 13306:3306
    healthcheck:
      test: ['CMD', 'mariadb-admin', 'ping']
      timeout: 5s
      interval: 10s
      retries: 3
  mssql:
    image: mssql-local
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=passWORD1
      - MSSQL_DB=test
      - MSSQL_USER=sa
      - MSSQL_PASSWORD=passWORD1
    ports:
      - 14339:1433
    healthcheck:
      test: ['CMD', 'ping']
      timeout: 5s
      interval: 10s
      retries: 3
